### PR TITLE
removed potential for an expired attestation to override the status of a control from being 'not reviewed'

### PR DESCRIPTION
**Pull request by Amndeep7**
resolves https://github.com/mitre/heimdall2/issues/4524

### CODE REVIEW

**Review by ejaronne — APPROVED** [review]
LGTM!
image
Question though: Where is the "Attestation for control ${this.wraps.id} exists with invalid status: ${this.attestationStatus}" message expected to appear? I didn't see it in the Heimdall pop-up.

**Comment by wdower** [comment]
@Amndeep7 Do we have unit tests for attestations specifically? Do we have one that confirms expired attestations fail?

**Comment by Amndeep7** [comment]
@wdower i don't think hdf converters / inspecjs have any tests for attestations.  the saf cli has several w/r to making/parsing attestations.

**Comment by DMedina6** [comment]
Pulled master in again, and I am able to recreate this behavior after running the attestation tests again, running the frontend, and checking the outputted file.
image

**Pull request merged**
