### PR TITLE
Filtering on groups and tags

### PR DESCRIPTION
**Pull request by samcornwell**
First draft which has filename filtering working

Addresses #3857

### CODE REVIEW

**Comment by samcornwell** [comment]
Need to add tags filtering and test existing groups filtering

**Comment by samcornwell** [comment]
Re-opening to work on tags and groups now that filename filterint (#4471) is complete (pending final review)

**Comment by samcornwell** [comment]
Make sure to take care of these things per @Amndeep7 

https://github.com/mitre/heimdall2/pull/4471/files/74ec2c9d2b86bc008c4686ef4157b409565e1283#r1218497685
https://github.com/mitre/heimdall2/pull/4471/files/74ec2c9d2b86bc008c4686ef4157b409565e1283#r1217005337

**Comment by samcornwell** [comment]
Make sure to take care of these, per @Amndeep7

https://github.com/mitre/heimdall2/pull/4471#discussion_r1217005337
https://github.com/mitre/heimdall2/pull/4471#discussion_r1218497685

**Comment by samcornwell** [comment]
Group and tag filters appear too be working

**Comment by samcornwell** [comment]
Question: should tag and group filters only work with exact matches? For example, if a Results evaluation has a tag "HelloWorld", should it match if you type in the filter "tag:Hello", or no?

**Review by ejaronne — APPROVED** [review]
LGTM

**Comment by ejaronne** [comment]
Change "Filtered files" to "Filtered-out result sets"
Change "File Filters:" to "Result Set Filters:"

**Comment by samcornwell** [comment]
I noticed that I put a note above to address a comment @Amndeep7 made in my last PR (https://github.com/mitre/heimdall2/pull/4471#discussion_r1217005337). I'll have to examine this again if we need this for this PR, but I'm thinking I may need some help to address which filtering properties should apply to which "file type" (these being Result Sets, Profiles, and Checklists).

**Pull request merged**
