### PR TITLE
Vertically Slim UI, Enhance Focus, Pin ResponsiveRowSwitch and ControlRowHeader

### LINKED ISSUE #104: Vertically Slim, Focus, Pin experience/interaction
- [x] Vertically slim = reduce the vertical padding. everywhere. to almost nothing. change the paradigm to "the functionality is there, now let's add a little padding here and there".

- [x] Focus = for example, when binking on the results view table,  slide the top of the table to the top of the page. If I'm going to look at stuff there, I don't plan to work down in 1/4 of the bottom half of the page. Slide it up so I can see what I'm after!

- [x] Pin = For example, when I expand a row for a result (e.g., V-#), "pin" the row header at the top of the results view. That way, if I scroll down to look at test results or details or especially that very tall code block, I can still recall wth V-# I'm reviewing. 

- [x] Datatable - Remove "Single Expand" toggle. The "Status, ID, Severity, Title, and 800-53 Controls & CCIs" should stick to the top of the page as the user scrolls, and the currently expanded control heading should also stick if it is expanded.

- [x] Datatable - Remove nested datatable and make the datatable part of the page. (Fixed in #162)

### PR DESCRIPTION
**Pull request by camdenmoors**
Closes #104, changes:

- [x] Pin = For example, when I expand a row for a result (e.g., V-#), "pin" the row header at the top of the results view. That way, if I scroll down to look at test results or details or especially that very tall code block, I can still recall wth V-# I'm reviewing. 
- [x] Vertically slim = reduce the vertical padding. everywhere. to almost nothing. change the paradigm to "the functionality is there, now let's add a little padding here and there".

- [x] Focus = for example, when binking on the results view table,  slide the top of the table to the top of the page. If I'm going to look at stuff there, I don't plan to work down in 1/4 of the bottom half of the page. Slide it up so I can see what I'm after!

- [x] Datatable - Remove "Single Expand" toggle (Uncertain if we are still doing this). The "Status, ID, Severity, Title, and 800-53 Controls & CCIs" should stick to the top of the page as the user scrolls, and the currently expanded control heading should also stick if it is expanded.

### CODE REVIEW

**Comment by ejaronne** [comment]
When viewing results, please pin the results table part with the slider controls and the Test/Details/Controls sub-tab labels:
image

**Comment by ejaronne** [comment]
(sound on)

https://user-images.githubusercontent.com/34140975/112570746-0492d880-8dbd-11eb-9c0a-4c8f98ac2323.mp4

**Comment by ejaronne** [comment]
The items in the video seemed to be fixed, thanks! Are you still working on pinning the Results View Data - Sync Tabs - Single Expand - Expand All row?  If I get way down the results list and forgot to select, say, sync tabs, I have to scroll all the way up to the top again.

**Review by rbclark — CHANGES_REQUESTED** [review]
- [x] Test | Details | Code tabs jump slightly under the control row headers.
- [x] Test tab no longer underlines when expanded, it does it later on click.
- [x] There is too much space when scrolling down between the pinned headers and the control row, it makes it very easy to see above which is a little confusing.
- [x] Spaces in the key name breaks the jump to the jump to top for headings.

**Comment by rbclark** [comment]
> When viewing results, please pin the results table part with the slider controls and the Test/Details/Controls sub-tab labels:
> image

This is actually a much more difficult ask than it seems Eugene. How much time are you willing to have us put into this specific part of the feature?

**Comment by ejaronne** [comment]
> > When viewing results, please pin the results table part with the slider controls and the Test/Details/Controls sub-tab labels:
> > image
> 
> This is actually a much more difficult ask than it seems Eugene. How much time are you willing to have us put into this specific part of the feature?

We can skip this feature (Test/Details/Controls sub-tabs) for this release, thank you! It looks like you have been able to pin the table part with the slider controls though?

**Comment by rbclark** [comment]
> > > When viewing results, please pin the results table part with the slider controls and the Test/Details/Controls sub-tab labels:
> > > image
> > 
> > 
> > This is actually a much more difficult ask than it seems Eugene. How much time are you willing to have us put into this specific part of the feature?
> 
> We can skip this feature (Test/Details/Controls sub-tabs) for this release, thank you! It looks like you have been able to pin the table part with the slider controls though?

Correct, pinning the table part with the slider controls was possible.

**Review by rbclark — APPROVED** [review]

**Comment by rbclark** [comment]
@ejaronne this is now just awaiting your review before being merged.

**Review by ejaronne — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
