### PR TITLE
CAAT Enhancements

### LINKED ISSUE #770: CAAT enhancements
{This seems like an easy fix for a new SAF team member.}

- [x] include message field in the "Test Result Description" for both failed *and passed* controls. 
_(Because the message field is now populated for attested "passed" controls using the new inspec-reporter-json-hdf plugin.)_

Include *all* results in the CAAT output, not just ones that are passed or failed or impact != 0.0.
Here's how to populate their differences:
- [x] for skipped controls, include status (skipped) and "skip_message" field in "Test Result Description" field
- [x] for skipped controls (status of "skipped"), set "Test Result" to "Other Than Satisfied"
- [x] for results with impact 0.0 (N/A), set "Impact" field to "none"

Readability:
- [x] Fix the conversion of \n to the type of line feeds used in Excel, especially for "Weakness Description" (desc) "Test Objective" (tag check or desc check), "Test Result Description" (status + message/skip_message), and "Recommended Corrective Actions" (tag fix or desc fix).
fixes #58 

One small additional tweak I've been meaning to mention:
- [x] for "Impact" field, it was supposed to say "Moderate" for what we call "Medium"

### PR DESCRIPTION
**Pull request by camdenmoors**
Closes #770, includes all controls in CAAT export not just ones with impact, replaces all newlines with \r\n for carriage return, and adds attestation explanation to Test Result Description.

### CODE REVIEW

**Comment by rbclark** [comment]
@ejaronne Can you verify that the netlify preview on this PR includes all of the CAAT data you'd expect to see?

**Review by ejaronne — CHANGES_REQUESTED** [review]
[ATTESTATION-message]:
This is the message field in json:
image
and this is how it looks in Heimdall:
image
But this is all that shows up in the CAAT:
image
Please have it look like it does in Heimdall using the message block with all fields. Thanks!

[Skipped items]
image
I meant to *keep* the "Test Result" column as "Other Than Satisfied" for skipped items.

[FIX-TEXT BUG]
Apparently there is a different pre-existing problem on Fix text:
This is in json:
image
and this in Heimdall:
image
But this is all that shows up in CAAT:
image
Please try to figure this add-on bug fix if you can. Thanks!

**Comment by camdenmoors** [comment]
Unable to replicate the issue where the fix text isn't shown in full, please let me know if you still experience this.
image

**Comment by ejaronne** [comment]
RE:
    [Skipped items]
    image
    I meant to keep the "Test Result" column as "Other Than Satisfied" for skipped items.

What I meant is:
Not this:
image
But this:
image

I had trouble finding the test result (column P) in the code, but the only allowed values in that column are "Satisfied" and "Other Than Satisfied"

**Comment by ejaronne** [comment]
> I'm unable to replicate the issue where the fix text isn't shown in full, please let me know if you still experience this.
> image
Yeah, it does seem to be working now, not sure what happened before
image

**Comment by ejaronne** [comment]
Some more refinements (almost there! thanks!) Loading the sample Red_Hat_7_STIG_Baseline from heimdall itself:

Before:
image
After:
image

Before:
image
After:
image

Before:
image
After:
image

Before:
image
After:
image

Before:
image
After:
image

**Review by ejaronne — CHANGES_REQUESTED** [review]
Please see comments:
https://github.com/mitre/heimdall2/pull/1011#issuecomment-794814148 
and
https://github.com/mitre/heimdall2/pull/1011#issuecomment-794819753

**Review by ejaronne — APPROVED** [review]

**Pull request merged**
