### PR TITLE
Add Incorrect Password Message to User Profile

### LINKED ISSUE #475: [BUG] User profile edit provides unhelpful error if the currentPassword is incorrect
**Describe the bug**
The user info modal is currently not displaying a very helpful error message if the currentPassword is incorrect.

**To Reproduce**
1. Go to User icon
2. Click on User Info
3. Put in an incorrect current users password.

**Expected behavior**
A user should be able to update their profile and be provided with clear error messages when they provide incorrect information.

**Screenshots**
Screen Shot 2020-11-10 at 9 00 26 PM

### PR DESCRIPTION
**Pull request by camdenmoors**
Closes #475. Adds an Incorrect Password message if you input the wrong password.

### CODE REVIEW

**Review by rbclark — CHANGES_REQUESTED** [review]
This message doesn't actually seem to be propagating back through to the frontend (I'm using the server deploy preview):

Screen Shot 2020-11-16 at 1 28 14 PM

**Comment by camdenmoors** [comment]
> This message doesn't actually seem to be propagating back through to the frontend (I'm using the server deploy preview):

Strange, it works fine for me
image

**Comment by ejaronne** [comment]
When user puts in the incorrect password the response looks good.  
If the current password field is left blank and one hits save changes, instead of "CurrentPassword should not be empty", say "Please provide your current password to save changes to your profile"

Also: for clarity, please change "Current Password" to "Please provide your current password to save changes to your profile"

**Comment by ejaronne** [comment]
Is https://github.com/mitre/heimdall2/pull/500#issuecomment-728378203 still being worked? Not sure when I should review.

**Comment by rbclark** [comment]
> Is [#500 (comment)](https://github.com/mitre/heimdall2/pull/500#issuecomment-728378203) still being worked? Not sure when I should review.

Yes, Camden is working on this today.

**Review by rbclark — APPROVED** [review]

**Comment by ejaronne** [comment]
Looks good. Thanks!

**Pull request merged**
