### PR TITLE
Clarify XCCDF Results import scope

### PR DESCRIPTION
**Pull request by ejaronne**

### CODE REVIEW

**Review by Amndeep7 — APPROVED** [review]

**Comment by aaronlippold** [comment]
Is there anything we can add to the fingerprinting to know if the XCCDF-Results file came from a supported tool? Is there anything in the header that ids which client produced the file?

**Comment by aaronlippold** [comment]
Users don't RTFM so if our loading could say - I know you tried to give me an XCCDF-Results file but it doesn't seem to be from OpenSCAP or SCC or ACAS etc

**Comment by Amndeep7** [comment]
@aaronlippold maybe?  I would feel uncomfortable relying on it due to the low number of samples that we have but please see the following:

image

image

They're in two different locations and seem to be optionally supplied.  If we have other/older samples that we can also test with to see if the behavior stays the same over time, maybe it's possible?  The SCC one in particular I dunno if it's intentional or just a fluke for how Cole set up his vm / scc run.

**Comment by Amndeep7** [comment]
@mergifyio refresh

**Pull request merged**
