### PR TITLE
Add `None` category to severity summary chart

### PR DESCRIPTION
**Pull request by charleshu-8**
- Add `None` category
- Update summary chart generation for new field

### CODE REVIEW

**Comment by charleshu-8** [comment]
Generated summary charts using Red Hat 7 STIG Baseline:

Screenshot 2023-07-20 at 3 13 03 PM (2)

**Review by ejaronne — APPROVED** [review]
LGTM!

**Review by em-c-rod — APPROVED** [review]
Thanks, Charles :+1:

**Review by Amndeep7 — CHANGES_REQUESTED** [review]
I thought we were going to have this change happen against @ChrisHinchey's checklist viewer / filtering revision work since these files have been significantly changed.  If we want to backport this fix to current master that's fine I guess.  Additionally, please don't forget to make the change against the HTML export rework.

I will update the issue to make sure that those two locations where this change needs to happen are also tracked.

**Review by Amndeep7 — APPROVED** [review]

**Pull request merged**
