### PR TITLE
Draft: Add converter for grype reports

### PR DESCRIPTION
**Pull request by N1KN1M**
Resolves https://github.com/mitre/heimdall2/issues/2778

Related: https://github.com/anchore/grype/issues/701

Initial changes to standardize grype reports with the heimdall format.

No tests have been written yet.

The mappings and fingerprinting have to be agreed upon first.

### CODE REVIEW

**Comment by Amndeep7** [comment]
Hi @N1KN1M!  Thank you for this contribution!  It looks like you're asking for some guidance on how to move forward with developing this mapper.  Please send me an email at amann@mitre.org, and we can set up a quick call to discuss our typical process and answer any questions of yours.

**Comment by N1KN1M** [comment]
Hi @Amndeep7 , I'm trying to add the grype converter following the guidelines on https://github.com/mitre/heimdall2/issues/2778#issuecomment-1083647384

Since I'm not a core contributor to the grype project, I'd want someone from Grype to agree with the mappings before we proceed on this. 

From what I understand, the tests and the SAF cli integration are the only pieces pending once the fingerprinting and the mappings are agreed upon. I'm thinking of attaching a text containing simple dictionary like mapping to make it easier to read.

**Comment by Amndeep7** [comment]
Hi @N1KN1M, thanks for the work that you've done on this mapper.  I'd really appreciate it if you could write up a quick test and provide some sample files so that I can get a better understanding of the Grype format and ensure that its contents are properly being normalized into OHDF.  If you'd like to reach out to the Grype folks, that'd be great.  I'd first ask if they have a formal schema for their output format, which we could then use here.  After I'm comfortable with the mapper, we can reach out again to confirm that the mapper won't lose anything in the normalization process.

**Comment by N1KN1M** [comment]
@Amndeep7  I'd seen this detailed explanation of each required field in the mapper (https://saf.mitre.org/docs/mapper-background) after creating the initial changes, will ensure the values fit the bill as well as the grype schema before adding tests and taking this further

**Pull request closed without merging**
